services:
  app:
    build:
      context: ./app
      dockerfile: ./utils/Dockerfile
    container_name: flask-app
    ports:
      - "80:80"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - ./app:/app
    command: sh -c "gunicorn --bind 0.0.0.0:5000 wsgi:app &> logs/flask.log & nginx -g 'daemon off;'"
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
