name: Pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Pytests in Docker
        run: |
          docker compose -f docker-compose.test.yml up --abort-on-container-exit
        env:
          MONGO_URI: mongodb://mongo:27017/mydatabase

      - name: Clean up
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down --volumes